
-- SISTEMA DE GESTIÓN DE FACTURACIÓN MÉDICA
-- Universidad Fidélitas - Lenguaje de Base de Datos
-- Proyecto Final - Segundo Avance
-- Grupo 11
-- Archivo: 01_DDL_tablas.sql

-- SECCIÓN 1: LIMPIEZA (DROP EN ORDEN INVERSO DE DEPENDENCIAS)

BEGIN EXECUTE IMMEDIATE 'DROP TABLE AUDIT_FACTURA CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PAGO CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DETALLE_FACTURA CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE FACTURA CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CITA CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SERVICIO CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PACIENTE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MEDICO CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SEGURO_MEDICO CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE USUARIO_SISTEMA CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_FACTURA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- SECCIÓN 2: CREACIÓN DE TABLAS (EN ORDEN DE DEPENDENCIAS)

-- Tabla: SEGURO_MEDICO
CREATE TABLE SEGURO_MEDICO (
    ID_SEGURO              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE_ASEGURADORA     VARCHAR2(100) NOT NULL,
    NUMERO_POLIZA          VARCHAR2(50)  NOT NULL UNIQUE,
    COBERTURA_PORCENTAJE   NUMBER(5,2)   NOT NULL
        CONSTRAINT chk_cobertura CHECK (COBERTURA_PORCENTAJE BETWEEN 0 AND 100),
    FECHA_VENCIMIENTO      DATE          NOT NULL
);

-- Tabla: PACIENTE
CREATE TABLE PACIENTE (
    ID_PACIENTE      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_SEGURO        NUMBER,
    CEDULA           VARCHAR2(20)  NOT NULL UNIQUE,
    NOMBRE           VARCHAR2(100) NOT NULL,
    APELLIDOS        VARCHAR2(100) NOT NULL,
    FECHA_NACIMIENTO DATE          NOT NULL,
    TELEFONO         VARCHAR2(20)  NOT NULL,
    CORREO           VARCHAR2(100) NOT NULL,
    DIRECCION        VARCHAR2(200) NOT NULL,
    CONSTRAINT FK_PAC_SEGURO FOREIGN KEY (ID_SEGURO) REFERENCES SEGURO_MEDICO(ID_SEGURO)
);

-- Tabla: MEDICO
CREATE TABLE MEDICO (
    ID_MEDICO      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CEDULA         VARCHAR2(20)  NOT NULL UNIQUE,
    NOMBRE         VARCHAR2(100) NOT NULL,
    APELLIDOS      VARCHAR2(100) NOT NULL,
    ESPECIALIDAD   VARCHAR2(100) NOT NULL,
    CODIGO_MEDICO  VARCHAR2(50)  NOT NULL UNIQUE,
    TELEFONO       VARCHAR2(20)  NOT NULL,
    CORREO         VARCHAR2(100) NOT NULL
);

-- Tabla: CITA
CREATE TABLE CITA (
    ID_CITA         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_PACIENTE     NUMBER        NOT NULL,
    ID_MEDICO       NUMBER        NOT NULL,
    FECHA           DATE          NOT NULL,
    HORA            VARCHAR2(10)  NOT NULL,
    MOTIVO_CONSULTA VARCHAR2(500) NOT NULL,
    ESTADO          VARCHAR2(20)  NOT NULL
        CONSTRAINT chk_estado_cita CHECK (ESTADO IN ('PROGRAMADA','ATENDIDA','CANCELADA','NO_ASISTIO')),
    CONSTRAINT FK_CITA_PACIENTE FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID_PACIENTE),
    CONSTRAINT FK_CITA_MEDICO   FOREIGN KEY (ID_MEDICO)   REFERENCES MEDICO(ID_MEDICO)
);

-- Tabla: SERVICIO
CREATE TABLE SERVICIO (
    ID_SERVICIO     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE_SERVICIO VARCHAR2(200) NOT NULL,
    DESCRIPCION     VARCHAR2(500) NOT NULL,
    PRECIO_BASE     NUMBER(10,2)  NOT NULL
        CONSTRAINT chk_precio CHECK (PRECIO_BASE > 0),
    CATEGORIA       VARCHAR2(100) NOT NULL
        CONSTRAINT chk_categoria CHECK (CATEGORIA IN ('CONSULTA','LABORATORIO','PROCEDIMIENTO','IMAGENOLOGIA','OTRO'))
);

-- Tabla: FACTURA
CREATE TABLE FACTURA (
    ID_FACTURA                 NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_CITA                    NUMBER        NOT NULL,
    NUMERO_FACTURA_ELECTRONICA VARCHAR2(50)  NOT NULL UNIQUE,
    FECHA_EMISION              DATE          NOT NULL,
    SUBTOTAL                   NUMBER(10,2)  NOT NULL,
    DESCUENTO                  NUMBER(10,2)  DEFAULT 0,
    IVA                        NUMBER(10,2)  NOT NULL,
    TOTAL                      NUMBER(10,2)  NOT NULL,
    ESTADO_PAGO                VARCHAR2(20)  NOT NULL
        CONSTRAINT chk_estado_factura CHECK (ESTADO_PAGO IN ('PENDIENTE','PAGADA','ANULADA','PARCIAL')),
    CONSTRAINT FK_FACT_CITA FOREIGN KEY (ID_CITA) REFERENCES CITA(ID_CITA)
);

-- Tabla: DETALLE_FACTURA
CREATE TABLE DETALLE_FACTURA (
    ID_DETALLE      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_FACTURA      NUMBER       NOT NULL,
    ID_SERVICIO     NUMBER       NOT NULL,
    CANTIDAD        NUMBER(5)    NOT NULL
        CONSTRAINT chk_cantidad CHECK (CANTIDAD > 0),
    PRECIO_UNITARIO NUMBER(10,2) NOT NULL,
    SUBTOTAL_LINEA  NUMBER(10,2) NOT NULL,
    CONSTRAINT FK_DET_FACTURA  FOREIGN KEY (ID_FACTURA)  REFERENCES FACTURA(ID_FACTURA),
    CONSTRAINT FK_DET_SERVICIO FOREIGN KEY (ID_SERVICIO) REFERENCES SERVICIO(ID_SERVICIO)
);

-- Tabla: PAGO
CREATE TABLE PAGO (
    ID_PAGO                NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_FACTURA             NUMBER       NOT NULL,
    FECHA_PAGO             DATE         NOT NULL,
    MONTO_PAGADO           NUMBER(10,2) NOT NULL
        CONSTRAINT chk_monto CHECK (MONTO_PAGADO > 0),
    METODO_PAGO            VARCHAR2(50) NOT NULL
        CONSTRAINT chk_metodo CHECK (METODO_PAGO IN ('EFECTIVO','TARJETA_CREDITO','TARJETA_DEBITO','TRANSFERENCIA','SEGURO')),
    REFERENCIA_TRANSACCION VARCHAR2(100),
    ESTADO                 VARCHAR2(20) NOT NULL
        CONSTRAINT chk_estado_pago CHECK (ESTADO IN ('APROBADO','RECHAZADO','PENDIENTE')),
    CONSTRAINT FK_PAGO_FACTURA FOREIGN KEY (ID_FACTURA) REFERENCES FACTURA(ID_FACTURA)
);

-- Tabla: USUARIO_SISTEMA
CREATE TABLE USUARIO_SISTEMA (
    ID_USUARIO      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE_USUARIO  VARCHAR2(50)  NOT NULL UNIQUE,
    CONTRASENA_HASH VARCHAR2(200) NOT NULL,
    ROL             VARCHAR2(50)  NOT NULL
        CONSTRAINT chk_rol CHECK (ROL IN ('ADMINISTRADOR','FACTURISTA','MEDICO','RECEPCIONISTA')),
    CORREO          VARCHAR2(100) NOT NULL UNIQUE,
    ACTIVO          NUMBER(1)     DEFAULT 1
        CONSTRAINT chk_activo CHECK (ACTIVO IN (0,1)),
    FECHA_CREACION  DATE          DEFAULT SYSDATE
);

-- Tabla: AUDIT_FACTURA (para triggers de auditoría)
CREATE TABLE AUDIT_FACTURA (
    ID_AUDIT        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_FACTURA      NUMBER       NOT NULL,
    ESTADO_ANTERIOR VARCHAR2(20),
    ESTADO_NUEVO    VARCHAR2(20),
    FECHA_CAMBIO    DATE         DEFAULT SYSDATE,
    USUARIO_BD      VARCHAR2(50) DEFAULT USER
);

-- SECCIÓN 3: SECUENCIAS

-- Secuencia para número de factura electrónica
CREATE SEQUENCE SEQ_FACTURA
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- SECCIÓN 4: DATOS INICIALES DE PRUEBA

-- Seguros médicos
INSERT INTO SEGURO_MEDICO (NOMBRE_ASEGURADORA, NUMERO_POLIZA, COBERTURA_PORCENTAJE, FECHA_VENCIMIENTO)
VALUES ('INS - Instituto Nacional de Seguros', 'INS-2024-001', 80, DATE '2026-12-31');

INSERT INTO SEGURO_MEDICO (NOMBRE_ASEGURADORA, NUMERO_POLIZA, COBERTURA_PORCENTAJE, FECHA_VENCIMIENTO)
VALUES ('ASSA Compañia de Seguros', 'ASSA-2024-005', 70, DATE '2026-06-30');

INSERT INTO SEGURO_MEDICO (NOMBRE_ASEGURADORA, NUMERO_POLIZA, COBERTURA_PORCENTAJE, FECHA_VENCIMIENTO)
VALUES ('Qualitas Compañia de Seguros', 'QUAL-2023-099', 60, DATE '2025-03-01');

-- Médicos
INSERT INTO MEDICO (CEDULA, NOMBRE, APELLIDOS, ESPECIALIDAD, CODIGO_MEDICO, TELEFONO, CORREO)
VALUES ('102340001', 'Carlos', 'Vargas Rojas', 'Medicina General', 'MG-0001', '8888-0001', 'c.vargas@clinica.cr');

INSERT INTO MEDICO (CEDULA, NOMBRE, APELLIDOS, ESPECIALIDAD, CODIGO_MEDICO, TELEFONO, CORREO)
VALUES ('102340002', 'Ana', 'Jiménez Castro', 'Pediatría', 'PED-0002', '8888-0002', 'a.jimenez@clinica.cr');

INSERT INTO MEDICO (CEDULA, NOMBRE, APELLIDOS, ESPECIALIDAD, CODIGO_MEDICO, TELEFONO, CORREO)
VALUES ('102340003', 'Luis', 'Mora Ulate', 'Cardiología', 'CAR-0003', '8888-0003', 'l.mora@clinica.cr');

-- Pacientes
INSERT INTO PACIENTE (ID_SEGURO, CEDULA, NOMBRE, APELLIDOS, FECHA_NACIMIENTO, TELEFONO, CORREO, DIRECCION)
VALUES (1, '304560001', 'María', 'González Pérez', DATE '1985-04-15', '7070-1001', 'm.gonzalez@mail.com', 'San José, Curridabat');

INSERT INTO PACIENTE (ID_SEGURO, CEDULA, NOMBRE, APELLIDOS, FECHA_NACIMIENTO, TELEFONO, CORREO, DIRECCION)
VALUES (2, '304560002', 'Roberto', 'Solano Fallas', DATE '1972-11-30', '7070-1002', 'r.solano@mail.com', 'Desamparados, San José');

INSERT INTO PACIENTE (ID_SEGURO, CEDULA, NOMBRE, APELLIDOS, FECHA_NACIMIENTO, TELEFONO, CORREO, DIRECCION)
VALUES (NULL, '304560003', 'Elena', 'Campos Brenes', DATE '1990-07-22', '7070-1003', 'e.campos@mail.com', 'Heredia Centro');

-- Servicios
INSERT INTO SERVICIO (NOMBRE_SERVICIO, DESCRIPCION, PRECIO_BASE, CATEGORIA)
VALUES ('Consulta General', 'Consulta médica general 30 minutos', 15000, 'CONSULTA');

INSERT INTO SERVICIO (NOMBRE_SERVICIO, DESCRIPCION, PRECIO_BASE, CATEGORIA)
VALUES ('Hemograma Completo', 'Examen de sangre completo CBC', 8500, 'LABORATORIO');

INSERT INTO SERVICIO (NOMBRE_SERVICIO, DESCRIPCION, PRECIO_BASE, CATEGORIA)
VALUES ('Electrocardiograma', 'ECG de 12 derivaciones', 25000, 'PROCEDIMIENTO');

INSERT INTO SERVICIO (NOMBRE_SERVICIO, DESCRIPCION, PRECIO_BASE, CATEGORIA)
VALUES ('Radiografía de Tórax', 'Rx de tórax AP y lateral', 18000, 'IMAGENOLOGIA');

INSERT INTO SERVICIO (NOMBRE_SERVICIO, DESCRIPCION, PRECIO_BASE, CATEGORIA)
VALUES ('Consulta Pediátrica', 'Consulta médica pediátrica', 18000, 'CONSULTA');

-- Usuario administrador
INSERT INTO USUARIO_SISTEMA (NOMBRE_USUARIO, CONTRASENA_HASH, ROL, CORREO)
VALUES ('admin', 'ef92b778bafe771e89245b89ecbc08a44a4e166c06659911881f383d4473e94f', 'ADMINISTRADOR', 'admin@clinica.cr');

COMMIT;

PROMPT ✓ DDL y datos iniciales aplicados exitosamente.
