-- ============================================================
-- SISTEMA DE GESTIÓN DE FACTURACIÓN MÉDICA
-- Archivo: 04_vistas.sql
-- Total: 10 vistas
-- ============================================================

-- VW01: Citas completas con datos de paciente, médico y seguro
CREATE OR REPLACE VIEW vw_citas_completas AS
SELECT
    C.ID_CITA,
    TO_CHAR(C.FECHA, 'DD/MM/YYYY')            AS FECHA,
    C.HORA,
    C.MOTIVO_CONSULTA,
    C.ESTADO,
    P.ID_PACIENTE,
    P.CEDULA                                   AS CEDULA_PACIENTE,
    P.NOMBRE || ' ' || P.APELLIDOS            AS NOMBRE_PACIENTE,
    M.ID_MEDICO,
    M.NOMBRE || ' ' || M.APELLIDOS            AS NOMBRE_MEDICO,
    M.ESPECIALIDAD,
    NVL(S.NOMBRE_ASEGURADORA, 'Sin seguro')   AS ASEGURADORA,
    S.COBERTURA_PORCENTAJE
FROM CITA C
JOIN PACIENTE P      ON C.ID_PACIENTE = P.ID_PACIENTE
JOIN MEDICO   M      ON C.ID_MEDICO   = M.ID_MEDICO
LEFT JOIN SEGURO_MEDICO S ON P.ID_SEGURO = S.ID_SEGURO;

-- VW02: Facturas pendientes de cobro con datos del paciente
CREATE OR REPLACE VIEW vw_facturas_pendientes AS
SELECT
    F.ID_FACTURA,
    F.NUMERO_FACTURA_ELECTRONICA,
    TO_CHAR(F.FECHA_EMISION, 'DD/MM/YYYY')    AS FECHA_EMISION,
    F.TOTAL,
    F.ESTADO_PAGO,
    TRUNC(SYSDATE - F.FECHA_EMISION)          AS DIAS_VENCIDA,
    P.NOMBRE || ' ' || P.APELLIDOS            AS PACIENTE,
    P.CEDULA,
    P.TELEFONO,
    P.CORREO
FROM FACTURA F
JOIN CITA     C ON F.ID_CITA     = C.ID_CITA
JOIN PACIENTE P ON C.ID_PACIENTE = P.ID_PACIENTE
WHERE F.ESTADO_PAGO IN ('PENDIENTE', 'PARCIAL');

-- VW03: Pacientes con información de seguro y edad calculada
CREATE OR REPLACE VIEW vw_pacientes_con_seguro AS
SELECT
    P.ID_PACIENTE,
    P.CEDULA,
    P.NOMBRE || ' ' || P.APELLIDOS               AS NOMBRE_COMPLETO,
    fn_calcular_edad(P.FECHA_NACIMIENTO)          AS EDAD,
    P.TELEFONO,
    P.CORREO,
    P.DIRECCION,
    NVL(S.NOMBRE_ASEGURADORA, 'Sin seguro')       AS ASEGURADORA,
    S.NUMERO_POLIZA,
    S.COBERTURA_PORCENTAJE,
    CASE WHEN S.FECHA_VENCIMIENTO >= SYSDATE
         THEN 'VIGENTE' ELSE 'VENCIDA' END        AS ESTADO_POLIZA
FROM PACIENTE P
LEFT JOIN SEGURO_MEDICO S ON P.ID_SEGURO = S.ID_SEGURO;

-- VW04: Servicios agrupados por categoría con estadísticas de precio
CREATE OR REPLACE VIEW vw_servicios_por_categoria AS
SELECT
    CATEGORIA,
    COUNT(*)                     AS CANTIDAD_SERVICIOS,
    MIN(PRECIO_BASE)             AS PRECIO_MINIMO,
    MAX(PRECIO_BASE)             AS PRECIO_MAXIMO,
    ROUND(AVG(PRECIO_BASE), 2)  AS PRECIO_PROMEDIO
FROM SERVICIO
GROUP BY CATEGORIA
ORDER BY CATEGORIA;

-- VW05: Ingresos y citas atendidas por médico en el año actual
CREATE OR REPLACE VIEW vw_ingresos_por_medico AS
SELECT
    M.ID_MEDICO,
    M.NOMBRE || ' ' || M.APELLIDOS   AS MEDICO,
    M.ESPECIALIDAD,
    COUNT(DISTINCT C.ID_CITA)        AS CITAS_ATENDIDAS,
    NVL(SUM(PA.MONTO_PAGADO), 0)    AS INGRESOS_TOTALES
FROM MEDICO M
LEFT JOIN CITA    C  ON M.ID_MEDICO   = C.ID_MEDICO AND C.ESTADO = 'ATENDIDA'
LEFT JOIN FACTURA F  ON C.ID_CITA     = F.ID_CITA
LEFT JOIN PAGO    PA ON F.ID_FACTURA  = PA.ID_FACTURA
                     AND PA.ESTADO    = 'APROBADO'
                     AND EXTRACT(YEAR FROM PA.FECHA_PAGO) = EXTRACT(YEAR FROM SYSDATE)
GROUP BY M.ID_MEDICO, M.NOMBRE, M.APELLIDOS, M.ESPECIALIDAD;

-- VW06: Facturas con resumen de líneas de detalle
CREATE OR REPLACE VIEW vw_facturas_con_detalle AS
SELECT
    F.ID_FACTURA,
    F.NUMERO_FACTURA_ELECTRONICA,
    TO_CHAR(F.FECHA_EMISION, 'DD/MM/YYYY') AS FECHA_EMISION,
    F.SUBTOTAL,
    F.DESCUENTO,
    F.IVA,
    F.TOTAL,
    F.ESTADO_PAGO,
    COUNT(DF.ID_DETALLE)  AS CANTIDAD_ITEMS,
    SUM(DF.CANTIDAD)      AS UNIDADES_TOTALES
FROM FACTURA F
LEFT JOIN DETALLE_FACTURA DF ON F.ID_FACTURA = DF.ID_FACTURA
GROUP BY F.ID_FACTURA, F.NUMERO_FACTURA_ELECTRONICA, F.FECHA_EMISION,
         F.SUBTOTAL, F.DESCUENTO, F.IVA, F.TOTAL, F.ESTADO_PAGO;

-- VW07: Agenda del día actual (todas las citas de hoy)
CREATE OR REPLACE VIEW vw_citas_hoy AS
SELECT
    C.ID_CITA,
    C.HORA,
    P.NOMBRE || ' ' || P.APELLIDOS AS PACIENTE,
    P.CEDULA,
    P.TELEFONO,
    M.NOMBRE || ' ' || M.APELLIDOS AS MEDICO,
    M.ESPECIALIDAD,
    C.MOTIVO_CONSULTA,
    C.ESTADO
FROM CITA C
JOIN PACIENTE P ON C.ID_PACIENTE = P.ID_PACIENTE
JOIN MEDICO   M ON C.ID_MEDICO   = M.ID_MEDICO
WHERE TRUNC(C.FECHA) = TRUNC(SYSDATE)
ORDER BY C.HORA;

-- VW08: Resumen mensual de facturación
CREATE OR REPLACE VIEW vw_resumen_mensual AS
SELECT
    EXTRACT(YEAR  FROM F.FECHA_EMISION)                                                   AS ANIO,
    EXTRACT(MONTH FROM F.FECHA_EMISION)                                                   AS MES,
    COUNT(F.ID_FACTURA)                                                                   AS FACTURAS_EMITIDAS,
    SUM(CASE WHEN F.ESTADO_PAGO != 'ANULADA' THEN F.TOTAL ELSE 0 END)                   AS MONTO_FACTURADO,
    SUM(CASE WHEN F.ESTADO_PAGO = 'PAGADA'   THEN F.TOTAL ELSE 0 END)                   AS MONTO_COBRADO,
    SUM(CASE WHEN F.ESTADO_PAGO IN ('PENDIENTE','PARCIAL') THEN F.TOTAL ELSE 0 END)     AS MONTO_PENDIENTE,
    COUNT(CASE WHEN F.ESTADO_PAGO = 'ANULADA' THEN 1 END)                               AS FACTURAS_ANULADAS
FROM FACTURA F
GROUP BY EXTRACT(YEAR FROM F.FECHA_EMISION), EXTRACT(MONTH FROM F.FECHA_EMISION)
ORDER BY ANIO DESC, MES DESC;

-- VW09: Médicos agrupados por especialidad
CREATE OR REPLACE VIEW vw_medicos_especialidad AS
SELECT
    ESPECIALIDAD,
    COUNT(*) AS CANTIDAD_MEDICOS,
    LISTAGG(NOMBRE || ' ' || APELLIDOS, ' | ')
        WITHIN GROUP (ORDER BY APELLIDOS) AS LISTA_MEDICOS
FROM MEDICO
GROUP BY ESPECIALIDAD
ORDER BY ESPECIALIDAD;

-- VW10: Historial completo de pagos con datos de factura y paciente
CREATE OR REPLACE VIEW vw_historial_pagos AS
SELECT
    PA.ID_PAGO,
    TO_CHAR(PA.FECHA_PAGO, 'DD/MM/YYYY HH24:MI') AS FECHA_PAGO,
    PA.MONTO_PAGADO,
    PA.METODO_PAGO,
    PA.REFERENCIA_TRANSACCION,
    PA.ESTADO                                     AS ESTADO_PAGO,
    F.NUMERO_FACTURA_ELECTRONICA,
    F.TOTAL                                       AS TOTAL_FACTURA,
    F.ESTADO_PAGO                                 AS ESTADO_FACTURA,
    P.NOMBRE || ' ' || P.APELLIDOS               AS PACIENTE,
    P.CEDULA
FROM PAGO     PA
JOIN FACTURA  F  ON PA.ID_FACTURA  = F.ID_FACTURA
JOIN CITA     C  ON F.ID_CITA      = C.ID_CITA
JOIN PACIENTE P  ON C.ID_PACIENTE  = P.ID_PACIENTE
ORDER BY PA.FECHA_PAGO DESC;

PROMPT ✓ 10 vistas creadas exitosamente.
